apiVersion: backstage.io/alpha
kind: Component
metadata:
  name: ${{values.name | dump}}
  description: ${{values.description | dump}}
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo }}
spec:
  type: documentation
  lifecycle: experimental
  owner: ${{values.owner | dump}}
